name: build docker
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: run install
        shell: bash
        run: |
          npm install
          npm test
      - name: docker image
        if: github.ref.name == 'main'
        run: docker build -t ${{ github.sha }} .
