name: cache
on:
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: run install
        shell: bash
        run: |
          npm install
      - name: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules

      - name: run test
        shell: bash
        run: |
          npm test
